language: python
dist: xenial
python:
- 2.7
- 3.5
- 3.6
- 3.7
install: pip install tox-travis
script: tox
after_success: 
cache:
  pip: true
notifications:
  webhooks:
    secure: cETD6UGKQsCWfuLE0eAiRhzNd6JPvQ4HrR4pCehC8/sv1GyCrSFfjm725xOApstoqjK30YYjnzevkb+qDUlUHCSIygcmpkeFFelqX0dF79MFTaeGOmlaqMW9eU7IHd6WYAEE6MEDM5DKAfn8mH6g8F40IthIdJzpxPehucWA+9EGI8YVJIIuUwVdZC4Ro2FdcRdpYJeuJ7sjIgbLqmdCGc04TdM/N1aCXf7IRtbD721hm4SbRvOdSbU9tcrx5nxStwhuRnlOkD3vANbb9vY2mOMa4vklC4l/cyC9Am9RqrgazEDh9n8+qcnXFBuwgIIf/50HQfqlIZs8xTPJNZh6533gGYjGAfe8Q2BtTp/FvesJKaoRvufGrLglhSOplwdsToJZdAy5dWJmrZCyjK3rlxAWE96Mi/fCh7veybEF343snf6Jt5vIFubzBEaeHlIyiWzeWt25ECyae8SD/WxnSweRtvA7YuEbd2rwVIxR2Ju+inbtL6tbEf1bHmtnaQf2fwAhL0OHcuFS3fN7UT6Ay4ZnROwhmYaqe9OZyrNRXgXJ5QzuxrfKaNWCCXfPlAGIi6g15qLgBw9HJgwsGhqdcn7hzqiMgYAP1GFfvHy2QgFJsMlCwJv+QF8wej7d9pgsvmviK65sp0pzBB7ScE+VPqqLzuMuwC0TelKR7ck04N4=
